import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Notification from '@/components/Notification'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import AuthProvider from '@/components/AuthProvider'
import AuthLoadingPage from '@/components/AuthLoadingPage'
import QueryProvider from '@/components/QueryProvider'
import { ToastContainer } from 'react-toastify'
import "react-toastify/dist/ReactToastify.css";
import { EdgeStoreProvider } from './lib/edgestore'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
              <EdgeStoreProvider>
        <AuthProvider>
          <QueryProvider>
            <AuthLoadingPage>
                <Notification />
                <Navbar />
                {children}
                <Footer />
                <ToastContainer position='bottom-right' theme='dark' autoClose={3000} />
            </AuthLoadingPage>
          </QueryProvider>
        </AuthProvider>
              </EdgeStoreProvider>
        </body>
    </html>
  )
}